[env]
PORT="8000"
STORAGE_TYPE="in_memory" # or gcloud
ENCRYPTION_KEY="YzYzUyYzA2NWItYmE1YS00MDM3LWJkYt"

HCAPTCHA_SITE_KEY="10000000-ffff-ffff-ffff-000000000001"
HCAPTCHA_SECRET="0x0000000000000000000000000000000000000000"

GCLOUD_BUCKET="passdl"
GCLOUD_SERVICE_ACCOUNT=".sa.json"
