[package]
name = "secret-share"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
rand_core = { version = "0.6", features = ["std"] }
serde = "1"
serde_json = "1"
base64 = "0.13.0"