name: Build And Release

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GCP_REGION: us-central1
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SERVICE: images/secret-share

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          server/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cd server && cargo build --verbose --release

    - name: Test
      run: cd server && cargo test --verbose --release

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: server-build
        path: server/target/release/secret-share

  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build
      run: cd client && npm install && npm run build

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: client-build
        path: client/build

  release:
    needs: [build-server, build-client]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download Server
      uses: actions/download-artifact@v2
      with:
        name: server-build
        path: server/target/release

    - name: Download Client
      uses: actions/download-artifact@v2
      with:
        name: client-build
        path: client/build

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup GCloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize GCloud Docker push
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_SERVICE }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}